### ISSUE TITLE
Ngrok not generating a link.

### ISSUE THREAD

**Issue by hood1** [Stephin-Franklin/T-Phish#1] opened 2020-05-05 06:00 UTC
The Ngrok server pre-installed with the T-phish is not generating a link. I also try to deleted the Ngrok and downloaded a new one from Ngrok site and then install it but it keeps giving the same problem. 
Please, how can i solve this problem.
![Screenshot_20200505-065855](https://user-images.githubusercontent.com/64293471/81038471-03537700-8e9e-11ea-89a0-2d2ee526df1a.png)

**Comment by hdss1990** [comment] 2020-05-07 23:11
Dame issue here

**Comment by user420-ops** [comment] 2020-05-15 07:12
![Screenshot_2020-05-15-12-40-20-23](https://user-images.githubusercontent.com/65068758/82021986-7da7a680-96a9-11ea-8b8c-4efa6fff04d6.png)
Why this is not work

**Comment by hood1** [comment] 2020-05-18 23:42
To resolve this issue, it`s very simple, all you need to do is to power on your hotspot before launching the Ngrok server.

**Comment by thehackash** [comment] 2020-05-20 04:34
> To resolve this issue, it`s very simple, all you need to do is to power on your hotspot before launching the Ngrok serve
Duplicate of 

> To resolve this issue, it`s very simple, all you need to do is to power on your hotspot before launching the Ngrok server.

Its not even generating link after that, i have followed every Step and even my Ngrok server is  Online Come up with some better answer

**Comment by hood1** [comment] 2020-05-20 21:40
To resolve this, kindly follow the steps below carefully.
Step 1: Delete the ngrok in the T-phish folder. Use command:  rm -rf ngrok 
Step 2: Register on ngrok site and download a linux arm ngrok.
Step 3: unzip the ngrok zip file, use command: unzip ngrokfilename.zip
Step 4: copy the extracted file into the T-phish folder and also copy to the home folder.  Use command: cp -v ngrok /$HOME or /filedirectory
Step 5: use command: chmod +x ngrok , to change it mode. After that, copy the ngrok authentication file given to you after registering at the ngrok site. 
Step 6: use command: ./ngrok authtoken yourgiventoken
Step 7: launch T-phish or other app that uses ngrok and ON your hotspot while launching.
I believe it should start working with this little help.
This are samples of what i have done with it.
![Screenshot_20200520-223731](https://user-images.githubusercontent.com/64293471/82500244-edbf8d80-9aea-11ea-90a7-c7de1a4127c7.png)
![Screenshot_20200520-223846](https://user-images.githubusercontent.com/64293471/82500254-f0ba7e00-9aea-11ea-972f-6f342f565ee6.png)

**Comment by NganDii** [comment] 2020-05-27 10:45
1. Remove previous ngrok type rm -rf ngrok
2. Paste this..
cd && apt-get update -y && apt-get upgrade -y && pkg install git -y && git clone https://github.com/noob-hackers/tunnel && cd tunnel && bash tunnel.sh
3. Select 1 to Install ngrok.
4. Paste your ngrok token which is
./ngrok authtoken yourtokenhere
5. Remove ngrok from T-Phish directory too.. 
6. Paste this to copy ngrok to T-Phish folder
cd && cp ngrok T-Phish
7. Done

**Comment by NganDii** [comment] 2020-05-27 15:57
1. Remove ngrok if installed.
2. Copy your ngrok auth token from https://dashboard.ngrok.com/get-started/setup
3. Paste this..
cd $HOME && pkg update && pkg upgrade && pkg install git && git clone https://github.com/NganDii/T-Phish && cd T-Phish && bash Install.sh
4. Paste your ngrok token when asked and Boom!
5. It works without hotspot on.

Note: Stephin Sir I don't know if I am allowed but I made some changes and uploaded on my github account to make it work.

**Closed** 2020-05-28 08:31 UTC

**Comment by lightningbolt7** [comment] 2021-08-21 09:55
How do I do it on Kali Linux, plz help me

**Comment by Projectboyy** [comment] 2022-10-25 16:02
How do I do it on Kali Linux, plz help me!!!

**Comment by zelao12** [comment] 2023-08-11 11:57
how do i do it in kali

**Comment by DomoKrch** [comment] 2023-10-16 08:56
once ShellPhish activated Ngrok session, look for the address on localhost:4040

**Comment by narfnarf123** [comment] 2024-02-16 16:38
I cannot bring it to work either on Kali. Installed T-Phish, copied ngrok to home, inserted auth token via "./ngrok authtoken xxxxx"

Then starting T-Phish, choosing attack, ... , "Starting ngrok server" , needs ~10 seconds, but the "Send this link to target" information is completely empty.  

![grafik](https://github.com/Stefin-Franklin/T-Phish/assets/159151556/78d3857a-1e7f-4fd8-8dbd-984b1227e03d)

Using it with Kali VM on my Windows PC. VM has access to the internet, of cause, otherwise download would not work ...

Any ideas?

>     4. Paste your ngrok token when asked and Boom!

I was never asked about the token. 


└─$ ngrok config check
Valid configuration file at /home/kali/.config/ngrok/ngrok.yml

![grafik](https://github.com/Stefin-Franklin/T-Phish/assets/159151556/cf4d2cd4-13ae-4d86-9de8-f060a0e5d684)
